### ISSUE TITLE
newFARMap is adding empty forwardingParameters

### ISSUE THREAD

**Issue by ranomine** [nextmn/go-pfcp-networking#5]
Hi,

Creating a FAR as follows:
```
gtpFAR1 := ie.NewCreateFAR(
		ie.NewFARID(0x00000002),
		ie.NewApplyAction(0x0100))
```

which is valid.

I notice that NewFARMap is adding an empty forwardingParameters ie to the FAR like:
```
*github.com/wmnsk/go-pfcp/ie.IE {Type: 4, Length: 0, EnterpriseID: 0, Payload: []uint8 len: 0, cap: 0, [], ChildIEs: []*github.com/wmnsk/go-pfcp/ie.IE len: 0, cap: 0, nil}
```

**Comment by louisroyer** [comment]
Hi, could you test if 1b98989277a27ae371ed3bf0c70091cc92576c72 solves your issue (`go get -u github.com/louisroyer/go-pfcp-networking@ForwardingParametersEmpty`)?

I generally don't use DROP flag and since my FarMAP implementation is very minimal and focuses on what I needed to create an UPF (with a lots of feature missing), this case was untested.
I have planed to store all of this in a true database (because matching of existing rules is very slow at the moment, and my UPF's bit-rate is limited by it): this will allow to perform SQL requests and also handling of more FAR related IEs… but for the moment, I haven't found enough time to implement it.

**Comment by ranomine** [comment]
Hi,

I think that you need also to fix NewCreateFAR which is checking that far.forwardingParameters isn't nil
but far.ForwardingParameters() is actually returning an empty array instead of nil when the IE isn't present.
